### ISSUE TITLE
Integrate cloud upload from the agile UI. 

### ISSUE THREAD

**Issue by Exulansis** [Agile-IoT/agile-ui#60]
### Description

The Agile UI needs to render the fields required for cloud upload functionality, e.g. username, password, token. These fields depend on the cloud provider, and will be discovered automatically. The initial implementation will be geared towards OwnCloud.

### TODO:

- [ ] Discover available cloud providers and their required fields.
- [ ] Render relevant fields, and any extra specific elements, e.g. folder selection for Google drive.
- [ ] Allow the user to fetch credentials from agile data.
- [ ] Implement initial support for OwnCloud.
